[package]
name = "cms"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.1"
uuid = { version = "0.8", features = ["v4"] }
log = "0.4"